server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.7:3306/pet
  redis:
    #redis服务地址
    host: 192.168.0.7
    #redis连接端口
    port: 6379
    #redis数据库索引
    database: 0
    #连接超时时间(毫秒)
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数(使用负数表示不限制)
        max-active: 20
        #最大阻塞等待时间(使用负数表示不限制)
        max-wait: -1
        #最大空闲连接
        max-idle: 5
        #最小空闲连接
        min-idle: 0
logging:
  level:
    top.jolyoulu : debug